// Phase 12 — branded, numbered procurement PDF documents (pdfkit).
//
// Every catalog document renders through one branded layout: company header,
// document type + number, a meta block, a line table, a totals block and a
// per-page footer. The catalog documents:
//   PR, RFQ, quotation cover, technical evaluation, commercial comparison,
//   award recommendation, PO, delivery receipt, MIR, GRN, supplier return note.

'use strict';

const PDFDocument = require('pdfkit');

const BRAND = {
  name: process.env.COMPANY_NAME || 'Osiris Labs',
  tagline: process.env.COMPANY_TAGLINE || 'Construction ERP — Procurement',
  footer: 'System-generated by the Construction ERP procurement module.',
};

function fmt(n) {
  const v = parseFloat(n);
  return Number.isFinite(v) ? v.toLocaleString('en-US', { maximumFractionDigits: 3 }) : String(n == null ? '' : n);
}

function money(n) {
  const v = parseFloat(n);
  return Number.isFinite(v) ? v.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : String(v == null ? '' : v);
}

function num(n) {
  const v = parseFloat(n);
  return Number.isFinite(v) ? String(v) : String(n == null ? '' : n);
}

// renderDocument({ brand, docType, number, date, meta, columns, rows,
//                  summary, notes }) → Promise<Buffer>
async function renderDocument(spec) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 48, bufferPages: true });
      const chunks = [];
      doc.on('data', (c) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const left = 48;
      const pageWidth = doc.page.width - 96;

      // Branded header band.
      doc.rect(0, 0, doc.page.width, 78).fill('#1a3c5e');
      doc.fill('#ffffff').font('Helvetica-Bold').fontSize(16)
        .text(spec.brand || BRAND.name, left, 20);
      doc.font('Helvetica').fontSize(9)
        .text(BRAND.tagline, left, 42)
        .text(`${spec.docType || 'DOCUMENT'}${spec.number ? `  ${spec.number}` : ''}`, left, 56);

      doc.fillColor('#000000');
      let y = 100;

      doc.font('Helvetica-Bold').fontSize(14).fillColor('#1a3c5e').text(spec.docType || 'DOCUMENT', left, y);
      if (spec.date) {
        doc.font('Helvetica').fontSize(9).fillColor('#555555')
          .text(`Date: ${typeof spec.date === 'string' ? spec.date : new Date(spec.date).toISOString().slice(0, 10)}`,
            doc.page.width - 200 - 48, y + 2, { width: 200, align: 'right' });
      }
      y += 24;

      // Meta block.
      if (Array.isArray(spec.meta) && spec.meta.length) {
        doc.moveTo(left, y).lineTo(left + pageWidth, y).strokeColor('#cccccc').stroke();
        y += 10;
        for (const entry of spec.meta) {
          const [k, v] = entry;
          if (v == null) continue;
          doc.font('Helvetica-Bold').fontSize(9).fillColor('#333333')
            .text(`${k}:`, left, y, { continued: true, width: 140 })
            .font('Helvetica').fillColor('#000000').text(` ${v}`);
          y += 14;
        }
        y += 6;
      }

      // Line table.
      if (Array.isArray(spec.columns) && spec.columns.length) {
        y += 6;
        doc.font('Helvetica-Bold').fontSize(9).fillColor('#1a3c5e');
        let x = left;
        for (const col of spec.columns) {
          doc.text(col.label, x, y, { width: col.width, align: col.align || 'left' });
          x += col.width;
        }
        y += 14;
        doc.moveTo(left, y).lineTo(left + pageWidth, y).strokeColor('#1a3c5e').stroke();
        y += 5;
        doc.font('Helvetica').fontSize(9).fillColor('#000000');
        for (const row of spec.rows || []) {
          const heights = spec.columns.map((c) => doc.heightOfString(cellText(row, c), { width: c.width - 4 }));
          const rowHeight = Math.max(...heights, 12);
          if (y + rowHeight > doc.page.height - 70) { doc.addPage(); y = 60; }
          let cx = left;
          for (const col of spec.columns) {
            doc.text(cellText(row, col), cx, y, { width: col.width - 4, align: col.align || 'left' });
            cx += col.width;
          }
          y += rowHeight + 3;
        }
        y += 6;
      }

      // Totals block.
      if (Array.isArray(spec.summary) && spec.summary.length) {
        doc.moveTo(left, y + 2).lineTo(left + pageWidth, y + 2).strokeColor('#cccccc').stroke();
        y += 12;
        for (const [k, v] of spec.summary) {
          if (v == null) continue;
          doc.font('Helvetica-Bold').fontSize(10).fillColor('#333333')
            .text(`${k}:`, doc.page.width - 270, y, { width: 150, align: 'right', continued: true })
            .font('Helvetica')
            .text(typeof v === 'number' ? money(v) : String(v), doc.page.width - 116, y, { width: 68, align: 'right' });
          y += 16;
        }
      }

      // Notes.
      if (spec.notes) {
        y += 8;
        doc.font('Helvetica-Oblique').fontSize(9).fillColor('#555555')
          .text(spec.notes, left, y, { width: pageWidth });
      }

      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.font('Helvetica').fontSize(8).fillColor('#888888')
          .text(`${BRAND.footer} — ${spec.number || ''} — page ${i + 1} of ${range.count}`,
            left, doc.page.height - 40, { width: pageWidth, align: 'center', lineBreak: false });
      }
      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}

function cellText(row, col) {
  const raw = row[col.key];
  if (raw == null) return '';
  if (typeof raw === 'boolean') return raw ? 'Yes' : 'No';
  if (typeof raw === 'number' || (typeof raw === 'string' && /^-?\d+(\.\d+)?$/.test(raw))) return fmt(raw);
  return String(raw);
}

const LINE_COLUMNS = [
  { key: 'material', label: 'Material', width: 170 },
  { key: 'description', label: 'Description', width: 130 },
  { key: 'quantity', label: 'Qty', width: 55, align: 'right' },
  { key: 'unit', label: 'Unit', width: 50 },
  { key: 'unit_rate', label: 'Rate', width: 70, align: 'right' },
  { key: 'net', label: 'Net', width: 77, align: 'right' },
];

async function renderPurchaseRequestDocument(pr, lines, brand) {
  return renderDocument({
    brand,
    docType: 'PURCHASE REQUISITION',
    number: pr.request_number,
    date: pr.created_at,
    meta: [['Project', pr.project_id], ['Priority', pr.priority], ['Needed by', pr.needed_by], ['Title', pr.title]],
    columns: LINE_COLUMNS,
    rows: lines,
    summary: [['Estimated total', pr.amount]],
  });
}

async function renderRfqDocument(rfq, lines, vendorCount) {
  return renderDocument({
    docType: 'REQUEST FOR QUOTATION',
    number: rfq.rfq_number,
    date: rfq.created_at,
    meta: [['Project', rfq.project_id], ['Quotations due', rfq.due_date], ['Vendors invited', vendorCount]],
    columns: [
      { key: 'material', label: 'Material', width: 170 },
      { key: 'description', label: 'Description', width: 190 },
      { key: 'quantity', label: 'Qty', width: 70, align: 'right' },
      { key: 'unit', label: 'Unit', width: 122 },
    ],
    rows: lines,
  });
}

async function renderQuotationCoverDocument(quotation, supplierName, lines) {
  return renderDocument({
    docType: 'SUPPLIER QUOTATION COVER',
    number: quotation.quotation_number,
    date: quotation.created_at,
    meta: [
      ['Supplier', supplierName], ['Payment terms', quotation.payment_terms],
      ['Delivery terms', quotation.delivery_terms], ['Lead time (days)', quotation.lead_time_days],
      ['Warranty (months)', quotation.warranty_months], ['Valid until', quotation.valid_until],
    ],
    columns: [
      { key: 'material', label: 'Material', width: 170 },
      { key: 'quantity', label: 'Qty', width: 80, align: 'right' },
      { key: 'unit_price', label: 'Unit price', width: 120, align: 'right' },
      { key: 'total_price', label: 'Line total', width: 182, align: 'right' },
    ],
    rows: lines,
    summary: [['Subtotal', quotation.total_price], ['Tax', quotation.tax_amount]],
  });
}

async function renderTechnicalEvaluationDocument(rfq, evaluations) {
  return renderDocument({
    docType: 'TECHNICAL EVALUATION',
    number: `TE-RFQ-${rfq.id}`,
    date: new Date(),
    meta: [['RFQ', rfq.rfq_number]],
    columns: [
      { key: 'supplier', label: 'Vendor', width: 180 },
      { key: 'compliant', label: 'Compliant', width: 90 },
      { key: 'technical_score', label: 'Technical score', width: 120, align: 'right' },
      { key: 'deviations', label: 'Deviations', width: 162 },
    ],
    rows: evaluations,
    notes: 'Technical evaluation precedes the commercial comparison.',
  });
}

async function renderCommercialComparisonDocument(comparison) {
  return renderDocument({
    docType: 'COMMERCIAL COMPARISON',
    number: comparison.rfq_number,
    date: new Date(),
    meta: [['RFQ', comparison.rfq_number]],
    columns: [
      { key: 'supplier_name', label: 'Vendor', width: 130 },
      { key: 'compliant', label: 'Compliant', width: 70 },
      { key: 'lead_time_days', label: 'Lead (d)', width: 55, align: 'right' },
      { key: 'unit_price', label: 'Unit', width: 65, align: 'right' },
      { key: 'total_price', label: 'Total', width: 80, align: 'right' },
      { key: 'payment_terms', label: 'Payment terms', width: 152 },
    ],
    rows: comparison.rows,
    notes: 'Internal commercial document — vendor portals never receive competitor quotations.',
  });
}

async function renderAwardRecommendationDocument(rfq, recommendation) {
  return renderDocument({
    docType: 'AWARD RECOMMENDATION',
    number: rfq.rfq_number,
    date: new Date(),
    meta: [['RFQ', rfq.rfq_number], ['Recommended vendor', recommendation.supplier_name], ['Total price', recommendation.total_price]],
    notes: recommendation.reason || null,
    columns: [
      { key: 'supplier_name', label: 'Vendor', width: 200 },
      { key: 'compliant', label: 'Compliant', width: 90 },
      { key: 'total_price', label: 'Total', width: 162, align: 'right' },
    ],
    rows: recommendation.rows || [],
  });
}

async function renderPurchaseOrderDocument(po, poLines, supplierName) {
  return renderDocument({
    docType: 'PURCHASE ORDER',
    number: po.order_number,
    date: po.created_at,
    meta: [
      ['Supplier', supplierName || po.supplier_id], ['Project', po.project_id],
      ['Payment terms', po.payment_terms], ['Delivery terms', po.delivery_terms],
      ['Tolerance', po.tolerance_pct != null ? `${po.tolerance_pct}%` : null],
    ],
    columns: LINE_COLUMNS,
    rows: poLines,
    summary: [
      ['Taxes', po.taxes],
      ['Freight', po.freight],
      ['Approved charges', po.approved_charges],
      ['PO total', po.total_amount],
    ],
    notes: 'Deliveries are subject to inspection (MIR) before goods receipt.',
  });
}

async function renderDeliveryReceiptDocument(delivery, lines, poNumber) {
  return renderDocument({
    docType: 'DELIVERY RECEIPT',
    number: delivery.delivery_number,
    date: delivery.delivery_date,
    meta: [['PO', poNumber || delivery.purchase_order_id], ['Status', delivery.status]],
    columns: [
      { key: 'material', label: 'Material', width: 180 },
      { key: 'description', label: 'Description', width: 160 },
      { key: 'quantity', label: 'Qty delivered', width: 112, align: 'right' },
    ],
    rows: lines,
    notes: 'Received material is quarantined pending inspection (MIR).',
  });
}

async function renderMirDocument(mir, mirLines, deliveryNumber) {
  return renderDocument({
    docType: 'MATERIAL INSPECTION REQUEST',
    number: mir.mir_number,
    date: mir.created_at,
    meta: [['Delivery', deliveryNumber || mir.delivery_id], ['PO', mir.purchase_order_id], ['Status', mir.status]],
    columns: [
      { key: 'material', label: 'Material', width: 170 },
      { key: 'quantity', label: 'Qty delivered', width: 100, align: 'right' },
      { key: 'accepted_quantity', label: 'Accepted', width: 90, align: 'right' },
      { key: 'rejected_quantity', label: 'Rejected', width: 92, align: 'right' },
    ],
    rows: mirLines,
    notes: 'The inspection outcome drives the inventory quarantine gate.',
  });
}

async function renderGrnDocument(grn, grnLines, warehouseName) {
  return renderDocument({
    docType: 'GOODS RECEIPT NOTE',
    number: grn.grn_number,
    date: grn.created_at,
    meta: [['PO', grn.purchase_order_id], ['MIR', grn.mir_id], ['Warehouse', warehouseName || grn.warehouse_id]],
    columns: [
      { key: 'material', label: 'Material', width: 180 },
      { key: 'quantity', label: 'Accepted qty', width: 120, align: 'right' },
      { key: 'unit', label: 'Unit', width: 252 },
    ],
    rows: grnLines,
    notes: 'Accepted cumulative ≤ delivered cumulative ≤ ordered + tolerance.',
  });
}

async function renderSupplierReturnDocument(supplierReturn, returnLines, reason) {
  return renderDocument({
    docType: 'SUPPLIER RETURN NOTE',
    number: supplierReturn.return_number,
    date: supplierReturn.created_at,
    meta: [['GRN', supplierReturn.grn_id], ['Reason', reason || supplierReturn.reason]],
    columns: [
      { key: 'material', label: 'Material', width: 180 },
      { key: 'quantity', label: 'Qty returned', width: 120, align: 'right' },
      { key: 'notes', label: 'Notes', width: 252 },
    ],
    rows: returnLines,
    notes: 'Returned quantities leave stock through supplier_return movements.',
  });
}

module.exports = {
  BRAND,
  renderDocument,
  renderPurchaseRequestDocument,
  renderRfqDocument,
  renderQuotationCoverDocument,
  renderTechnicalEvaluationDocument,
  renderCommercialComparisonDocument,
  renderAwardRecommendationDocument,
  renderPurchaseOrderDocument,
  renderDeliveryReceiptDocument,
  renderMirDocument,
  renderGrnDocument,
  renderSupplierReturnDocument,
};
